import './styles.css';
import { api, login, logout, restoreSession } from './api.js';
import { canProduceOfficialPdf, downloadGatePassPdf, gatePassDocument } from './pdf.js';

const app = document.querySelector('#app');
const state = { profile: null, view: 'dashboard', selectedId: null, passes: [], inventory: [], consignees: [], organization: {}, notice: null };
const esc = (value = '') => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
const date = (value) => value ? new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(`${value}T00:00:00`)) : '—';
const label = (value) => String(value || '').replaceAll('_', ' ');
const caps = () => state.profile?.capabilities || {};
const role = () => state.profile?.user?.role;
const setNotice = (text, type = 'success') => { state.notice = { text, type }; };

function status(value) { return `<span class="status ${esc(value)}">${esc(label(value))}</span>`; }
function empty(text) { return `<div class="empty">${esc(text)}</div>`; }
function button(text, attrs = '', kind = '') { return `<button class="button ${kind}" ${attrs}>${text}</button>`; }
function input(labelText, name, value = '', attrs = '', wide = false) { return `<label class="field ${wide ? 'field-wide' : ''}">${labelText}<input name="${name}" value="${esc(value)}" ${attrs}></label>`; }
function area(labelText, name, value = '', wide = true) { return `<label class="field ${wide ? 'field-wide' : ''}">${labelText}<textarea name="${name}">${esc(value)}</textarea></label>`; }

function loginView() {
  app.innerHTML = `<section class="login-shell"><div class="login-card"><div class="login-story"><p class="brand-kicker">MATERIAL MOVEMENT CONTROL</p><h1 class="mt-7 text-5xl font-semibold tracking-tight">Every pass.<br>Every stage.<br>Accountable.</h1><p class="mt-7 max-w-md text-lg leading-8 text-cyan-50">A controlled desktop workspace for preparation, independent approval, physical pass-out, return and audit.</p><div class="mt-14 border-t border-white/20 pt-5 font-mono text-xs text-cyan-100">BACKEND AUTHORITATIVE · OFFLINE DEPLOYABLE</div></div><form id="loginForm" class="login-form"><div><p class="brand-kicker text-cyan-700">SECURE OPERATOR ACCESS</p><h2 class="mt-2 text-3xl font-semibold text-[#122f43]">Sign in to MGP</h2><p class="mt-2 text-sm text-slate-500">Use the role account provisioned by your MGP administrator.</p></div><div id="loginNotice"></div><label class="field">Email<input type="email" name="email" autocomplete="username" required></label><label class="field">Password<input type="password" name="password" autocomplete="current-password" required></label>${button('Sign in', 'type="submit"')}</form></div></section>`;
}

function navigation() {
  const items = [['dashboard', 'Overview'], ['passes', 'Gate passes']];
  if (caps().createGatePass) items.push(['create', 'Create pass']);
  items.push(['inventory', 'Inventory master'], ['consignees', 'Consignee master'], ['reports', 'Reports']);
  if (caps().audit) items.push(['audit', 'Audit log']);
  if (caps().manageUsers) items.push(['users', 'User master'], ['settings', 'Organization'], ['backup', 'Backup & restore']);
  return items.map(([id, text]) => `<button class="nav-link ${state.view === id ? 'active' : ''}" data-view="${id}"><span aria-hidden="true">${id === 'dashboard' ? '◈' : '›'}</span>${text}</button>`).join('');
}

function shell(title, subtitle, content) {
  const notice = state.notice ? `<div class="notice ${state.notice.type}">${esc(state.notice.text)}</div>` : '';
  state.notice = null;
  app.innerHTML = `<section class="app-shell"><aside class="sidebar"><div><p class="brand-kicker">MATERIAL GATE PASS</p><div class="brand-title">MGP Control Room</div><div class="brand-rule"></div><nav aria-label="Primary navigation">${navigation()}</nav></div><div class="mt-auto border-t border-white/10 pt-5 text-xs text-slate-400"><div class="font-mono text-[10px] tracking-[.12em] text-cyan-300">BACKEND AUTHORITATIVE</div><p class="mt-2 leading-5">Every transition is validated and recorded by the server.</p></div></aside><main class="main-content"><header class="topbar"><div><p class="page-eyebrow">${esc(role())} WORKSPACE</p><h1 class="page-title">${esc(title)}</h1><p class="page-subtitle">${esc(subtitle)}</p></div><div class="operator-card"><div><div class="text-sm font-semibold text-slate-800">${esc(state.profile.user.name)}</div><div class="mt-1"><span class="role-chip">${esc(role())}</span></div></div>${button('Sign out', 'data-action="logout"', 'secondary small')}</div></header>${notice}${content}</main></section>`;
}

async function loadMasters() { [state.inventory, state.consignees] = await Promise.all([api('/mgp/inventory'), api('/mgp/consignees')]); }
async function fetchPasses(filters = {}) { const query = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); state.passes = await api(`/mgp/gate-passes${query.size ? `?${query}` : ''}`); return state.passes; }

function actionButtons(pass) {
  const actions = [button('Open', `data-action="open-pass" data-id="${pass.id}"`, 'ghost small')];
  const mine = pass.created_by === state.profile.user.id || role() === 'ADMIN';
  if (pass.status === 'DRAFT' && mine) actions.push(button('Edit', `data-action="edit-pass" data-id="${pass.id}"`, 'small'), button('Submit', `data-action="transition" data-transition="submit" data-id="${pass.id}"`, 'small'));
  if (pass.status === 'NOT_APPROVED' && ['ADMIN', 'INVENTORY'].includes(role())) actions.push(button('Create revision', `data-action="revise-pass" data-id="${pass.id}"`, 'warning small'));
  if (pass.status === 'SUBMITTED' && caps().approve) actions.push(button('Approve', `data-action="transition" data-transition="approve" data-id="${pass.id}"`, 'small'), button('Reject', `data-action="transition" data-transition="reject" data-id="${pass.id}"`, 'danger small'));
  if (pass.status === 'APPROVED' && caps().security) actions.push(button('Pass out', `data-action="transition" data-transition="pass-out" data-id="${pass.id}"`, 'warning small'));
  if (pass.status === 'PASSED_OUT' && pass.pass_type === 'RETURNABLE' && caps().security) actions.push(button('Mark returned', `data-action="transition" data-transition="return" data-id="${pass.id}"`, 'small'));
  if (canProduceOfficialPdf(pass)) actions.push(button('Official PDF', `data-action="preview-pdf" data-id="${pass.id}"`, 'ghost small'));
  return `<div class="flex flex-wrap gap-1.5">${actions.join('')}</div>`;
}

function passTable(rows) {
  if (!rows.length) return empty('No gate passes match this operational queue.');
  return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Pass no.</th><th>Date</th><th>Consignee</th><th>Type</th><th>Status</th><th>Operational actions</th></tr></thead><tbody>${rows.map((pass) => `<tr><td><button class="font-mono font-semibold text-cyan-800 hover:underline" data-action="open-pass" data-id="${pass.id}">${esc(pass.pass_no)}</button>${pass.revision_no ? `<div class="mt-1 font-mono text-[10px] text-slate-500">REVISION ${pass.revision_no}</div>` : ''}</td><td>${date(pass.pass_date)}</td><td><strong>${esc(pass.consignee_name)}</strong><div class="mt-1 text-xs text-slate-500">${esc(pass.reference_no || 'No reference')}</div></td><td>${esc(label(pass.pass_type))}</td><td>${status(pass.status)}</td><td>${actionButtons(pass)}</td></tr>`).join('')}</tbody></table></div>`;
}

async function dashboardView() {
  const [overview, due, passes] = await Promise.all([api('/mgp/reports/overview'), api('/mgp/reports/returns-due'), fetchPasses()]);
  const count = (key) => overview.statuses.find((row) => row.status === key)?.count || 0;
  shell('Operational overview', 'Live server-calculated queues for your role and access scope.', `<section class="metric-grid"><article class="metric"><div class="metric-value">${passes.length}</div><div class="metric-label">Visible passes</div></article><article class="metric"><div class="metric-value">${count('SUBMITTED')}</div><div class="metric-label">Awaiting approval</div></article><article class="metric"><div class="metric-value">${count('PASSED_OUT')}</div><div class="metric-label">Outside gate</div></article><article class="metric"><div class="metric-value">${due.length}</div><div class="metric-label">Overdue returnable</div></article></section><section class="panel"><div class="toolbar"><div><h2 class="panel-title">Recent operational records</h2><p class="panel-note">Your role sees only records permitted by the server-side scope.</p></div>${caps().createGatePass ? button('Create gate pass', 'data-view="create"') : ''}</div>${passTable(passes.slice(0, 8))}</section>${due.length ? `<section class="panel"><h2 class="panel-title">Return attention</h2><p class="panel-note">Returnable material still marked as passed out after its expected return date.</p>${passTable(due)}</section>` : ''}`);
}

async function passesView() {
  await fetchPasses();
  shell('Gate pass register', 'Searchable server records with role-scoped actions and immutable workflow history.', `<section class="panel"><form id="filterForm" class="filter-grid">${input('Search', 'q', '', 'placeholder="Pass number, consignee, reference"')}<label class="field">Status<select name="status"><option value="">All statuses</option>${['DRAFT', 'SUBMITTED', 'APPROVED', 'NOT_APPROVED', 'PASSED_OUT', 'RETURNED'].map((value) => `<option value="${value}">${label(value)}</option>`).join('')}</select></label>${input('From date', 'from', '', 'type="date"')}${input('To date', 'to', '', 'type="date"')}<div class="flex gap-2">${button('Apply', 'type="submit"')}${caps().createGatePass ? button('Create', 'type="button" data-view="create"', 'secondary') : ''}</div></form></section><section class="panel"><div class="toolbar"><div><h2 class="panel-title">Gate pass records</h2><p class="panel-note">Drafts and rejected records remain traceable; they are never silently removed.</p></div><div class="font-mono text-xs text-slate-500">${state.passes.length} RECORDS</div></div>${passTable(state.passes)}</section>`);
}

function itemRow(item = {}) { return `<div class="item-row"><label class="field">Item code<input name="item_code" value="${esc(item.item_code || '')}"></label><label class="field">Material name<input name="item_name" value="${esc(item.item_name || '')}" required></label><label class="field">Quantity<input name="quantity" type="number" min="0.001" step="0.001" value="${esc(item.quantity || 1)}" required></label><label class="field">Unit<input name="unit_of_measure" value="${esc(item.unit_of_measure || 'NOS')}"></label>${button('Remove', 'type="button" data-action="remove-item"', 'danger small')}</div>`; }
function passForm(pass = null) {
  const org = state.profile.organization || {}; const p = pass || { pass_type: 'RETURNABLE', pass_date: new Date().toISOString().slice(0, 10), packages: 1, directorate: org.defaultDirectorate || '', project: org.defaultProject || '', items: [{}] };
  return `<section class="panel"><form id="passForm" data-id="${esc(p.id || '')}"><div class="form-grid"><label class="field">Pass type<select name="pass_type"><option value="RETURNABLE" ${p.pass_type === 'RETURNABLE' ? 'selected' : ''}>Returnable</option><option value="NON_RETURNABLE" ${p.pass_type === 'NON_RETURNABLE' ? 'selected' : ''}>Non-returnable</option></select></label>${input('Pass date', 'pass_date', p.pass_date, 'type="date" required')}${input('Expected return date', 'expected_return_date', p.expected_return_date || '', 'type="date"')} ${input('Directorate', 'directorate', p.directorate, 'required')}${input('Project', 'project', p.project, 'required')}${input('Packages', 'packages', p.packages, 'type="number" min="1" required')}<label class="field">Consignee master<select name="consignee_id"><option value="">Manual consignee</option>${state.consignees.map((consignee) => `<option value="${consignee.id}" ${p.consignee_id === consignee.id ? 'selected' : ''}>${esc(consignee.name)}</option>`).join('')}</select></label>${input('Consignee name', 'consignee_name', p.consignee_name, 'required')}${input('Reference number', 'reference_no', p.reference_no)}${area('Consignee address', 'consignee_address', p.consignee_address)}${input('Inventory number', 'inventory_no', p.inventory_no)}${input('Inventory holder', 'inventory_holder', p.inventory_holder)}${input('Vehicle number', 'vehicle_no', p.vehicle_no)}${input('Loaded in presence of', 'loaded_in_presence_of', p.loaded_in_presence_of)}${input('Carrier name', 'carrier_name', p.carrier_name)}${input('Carrier designation', 'carrier_designation', p.carrier_designation)}${area('Purpose', 'purpose', p.purpose)}${area('Authority', 'authority', p.authority)}</div><section class="mt-6 rounded-xl border border-slate-200 bg-slate-50 p-4"><div class="toolbar"><div><h2 class="panel-title">Material line items</h2><p class="panel-note">At least one normalized material record is required.</p></div>${button('Add material', 'type="button" data-action="add-item"', 'secondary small')}</div><div id="items" class="grid gap-3">${(p.items || [{}]).map(itemRow).join('')}</div></section><div class="mt-6 flex gap-2">${button(pass ? 'Save draft' : 'Create draft', 'type="submit"')}${button('Cancel', 'type="button" data-view="passes"', 'secondary')}</div></form></section>`;
}
async function createView(id = null) { await loadMasters(); let pass = null; if (id) pass = await api(`/mgp/gate-passes/${id}`); shell(id ? 'Edit draft gate pass' : 'Create gate pass', 'Official pass numbers are assigned atomically by the database.', passForm(pass)); }

function masterRows(type, rows) {
  const inventory = type === 'inventory';
  return rows.length ? rows.map((row) => `<tr><td>${inventory ? esc(row.item_code) : esc(row.name)}</td><td>${inventory ? esc(row.item_name) : esc(row.address || '—')}</td><td>${inventory ? esc(row.quantity) : esc(row.contact || '—')}</td><td>${caps().manageMasters ? `<div class="flex gap-1">${button('Edit', `data-action="edit-master" data-type="${type}" data-id="${row.id}"`, 'ghost small')}${button('Archive', `data-action="archive-master" data-type="${type}" data-id="${row.id}"`, 'danger small')}</div>` : '<span class="text-slate-500">Read-only</span>'}</td></tr>`).join('') : `<tr><td colspan="4" class="text-center text-slate-500">No active records.</td></tr>`;
}
function masterForm(type, row = {}) { const inventory = type === 'inventory'; return `<form id="masterForm" class="mt-5 rounded-xl border border-cyan-200 bg-cyan-50 p-4" data-type="${type}" data-id="${esc(row.id || '')}"><h3 class="mb-4 font-semibold text-cyan-950">${row.id ? 'Edit' : 'Add'} ${inventory ? 'inventory item' : 'consignee'}</h3><div class="form-grid">${inventory ? `${input('Item code', 'item_code', row.item_code, 'required')}${input('Item name', 'item_name', row.item_name, 'required')}${input('Quantity', 'quantity', row.quantity ?? 0, 'type="number" min="0" step="0.001"')}${input('Category', 'category', row.category)}${input('Serial number', 'serial_no', row.serial_no)}${input('Batch number', 'batch_no', row.batch_no)}${input('Unit', 'unit_of_measure', row.unit_of_measure || 'NOS')}${input('Holder', 'holder', row.holder)}${area('Description', 'description', row.description)}` : `${input('Name', 'name', row.name, 'required')}${input('Contact', 'contact', row.contact)}${area('Address', 'address', row.address)}`}</div><div class="mt-4 flex gap-2">${button('Save', 'type="submit"')}${button('Cancel', 'type="button" data-action="cancel-master"', 'secondary')}</div></form>`; }
async function mastersView(type) { await loadMasters(); const inventory = type === 'inventory'; const rows = inventory ? state.inventory : state.consignees; const title = inventory ? 'Inventory master' : 'Consignee master'; const canExport = ['ADMIN', 'INVENTORY', 'ISSUING'].includes(role()); shell(title, 'Archived master records remain historically traceable and are never hard-deleted.', `<section class="panel"><div class="toolbar"><div><h2 class="panel-title">Active ${inventory ? 'materials' : 'consignees'}</h2><p class="panel-note">Use the master to standardize recurring operational data.</p></div><div class="flex gap-2">${canExport ? button('Export CSV', `data-action="export-master" data-type="${type}"`, 'ghost') : ''}${caps().manageMasters ? button(`Add ${inventory ? 'item' : 'consignee'}`, `data-action="new-master" data-type="${type}"`) : ''}</div></div><div id="masterEditor"></div><div class="table-wrap"><table class="data-table"><thead><tr><th>${inventory ? 'Item code' : 'Name'}</th><th>${inventory ? 'Material' : 'Address'}</th><th>${inventory ? 'Quantity' : 'Contact'}</th><th>Actions</th></tr></thead><tbody>${masterRows(type, rows)}</tbody></table></div></section>`); }

async function reportsView() { const [overview, due] = await Promise.all([api('/mgp/reports/overview'), api('/mgp/reports/returns-due')]); shell('Operational reports', 'Server-calculated role-scoped reporting. Exports should be retained according to your organization policy.', `<section class="panel"><h2 class="panel-title">Status distribution</h2><div class="metric-grid mt-4">${overview.statuses.map((row) => `<article class="metric"><div class="metric-value">${esc(row.count)}</div><div class="metric-label">${esc(label(row.status))}</div></article>`).join('') || empty('No reportable passes in your current scope.')}</div></section><section class="panel"><h2 class="panel-title">Due-return exceptions</h2><p class="panel-note">Returnable passes still outside after their expected return date.</p><div class="mt-4">${passTable(due)}</div></section>`); }
async function auditView() { const rows = await api('/mgp/events'); shell('Immutable audit log', 'Server-generated events; no MGP role can edit or delete audit entries.', `<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Time</th><th>Action</th><th>Pass</th><th>Transition</th><th>Actor role</th><th>Reason</th></tr></thead><tbody>${rows.map((row) => `<tr><td>${esc(new Date(row.created_at).toLocaleString('en-IN'))}</td><td class="font-mono text-xs">${esc(row.action)}</td><td>${esc(row.gate_pass_id || 'System')}</td><td>${esc(row.from_status || '—')} → ${esc(row.to_status || '—')}</td><td>${esc(row.actor_role)}</td><td>${esc(row.reason || '—')}</td></tr>`).join('') || `<tr><td colspan="6">No audit events.</td></tr>`}</tbody></table></div></section>`); }
async function usersView() { const users = await api('/mgp/users'); shell('User master', 'Only MGP application accounts are shown. The technical Directus Administrator is intentionally excluded.', `<section class="panel"><div class="toolbar"><div><h2 class="panel-title">MGP operators</h2><p class="panel-note">Provision a role account with a temporary password of at least 12 characters.</p></div>${button('Add MGP user', 'data-action="new-user"')}</div><div id="userEditor"></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Action</th></tr></thead><tbody>${users.map((user) => `<tr><td>${esc([user.first_name, user.last_name].filter(Boolean).join(' ') || '—')}</td><td>${esc(user.email)}</td><td>${esc(user.role_name)}</td><td>${esc(user.status)}</td><td>${button('Edit', `data-action="edit-user" data-user="${encodeURIComponent(JSON.stringify(user))}"`, 'ghost small')}</td></tr>`).join('') || `<tr><td colspan="5">No MGP users.</td></tr>`}</tbody></table></div></section>`); }
function userForm(user = {}) { const currentRole = Object.entries({ ADMIN: 'MGP Admin', INVENTORY: 'Inventory Holder', ISSUING: 'Issuing Officer', SECURITY: 'Security Officer', VIEWER: 'Viewer' }).find(([, name]) => name === user.role_name)?.[0] || 'INVENTORY'; return `<form id="userForm" class="mt-5 rounded-xl border border-cyan-200 bg-cyan-50 p-4" data-id="${esc(user.id || '')}"><h3 class="mb-4 font-semibold text-cyan-950">${user.id ? 'Edit MGP user' : 'New MGP user'}</h3><div class="form-grid">${!user.id ? input('Email', 'email', '', 'type="email" required') : ''}${input('First name', 'first_name', user.first_name)}${input('Last name', 'last_name', user.last_name)}<label class="field">Role<select name="role">${Object.entries({ ADMIN: 'MGP Admin', INVENTORY: 'Inventory Holder', ISSUING: 'Issuing Officer', SECURITY: 'Security Officer', VIEWER: 'Viewer' }).map(([code, name]) => `<option value="${code}" ${currentRole === code ? 'selected' : ''}>${name}</option>`).join('')}</select></label><label class="field">Status<select name="status"><option value="active" ${user.status === 'active' ? 'selected' : ''}>Active</option><option value="suspended" ${user.status === 'suspended' ? 'selected' : ''}>Suspended</option></select></label>${input(user.id ? 'New temporary password (optional)' : 'Temporary password', 'password', '', user.id ? 'type="password" minlength="12"' : 'type="password" minlength="12" required')}</div><div class="mt-4 flex gap-2">${button(user.id ? 'Save user' : 'Create user', 'type="submit"')}${button('Cancel', 'type="button" data-action="cancel-user"', 'secondary')}</div></form>`; }
async function settingsView() { const organization = await api('/mgp/settings/organization'); state.organization = organization; shell('Organization settings', 'Displayed on official documents and used as defaults for new gate passes.', `<section class="panel"><form id="settingsForm"><div class="form-grid">${input('Organization name', 'name', organization.name, 'required')}${input('Default directorate', 'defaultDirectorate', organization.defaultDirectorate)}${input('Default project', 'defaultProject', organization.defaultProject)}${area('Organization address', 'address', organization.address)}</div><div class="mt-5">${button('Save organization settings', 'type="submit"')}</div></form></section>`); }
async function backupView() { const backup = await api('/mgp/backup/status'); shell('Backup & restore guidance', 'Recovery actions stay outside the application and must be validated in an isolated database.', `<section class="panel"><h2 class="panel-title">Current backup signal</h2><p class="mt-3 text-sm">Last successful host backup: <strong>${esc(backup.lastSuccessfulAt || 'Not recorded')}</strong></p></section><section class="panel"><h2 class="panel-title">Safe recovery procedure</h2><ol class="mt-4 list-decimal space-y-2 pl-5 text-sm text-slate-600"><li>Run the authenticated host backup script and retain its checksum.</li><li>Run restore validation against an isolated disposable PostgreSQL instance.</li><li>Record the validation result in operational evidence before considering any production recovery.</li></ol><pre class="mt-5 overflow-x-auto rounded-lg bg-slate-950 p-4 font-mono text-xs text-cyan-100">./scripts/backup.sh\n./scripts/restore-validate.sh /path/to/backup.dump</pre></section>`); }
async function detailView(id) { const pass = await api(`/mgp/gate-passes/${id}`); state.selectedId = pass.id; shell(`Gate pass ${pass.pass_no}`, 'Full operational record with actions controlled by server-side role and state validation.', `<section class="panel"><div class="toolbar"><div><div class="flex items-center gap-3"><h2 class="panel-title font-mono">${esc(pass.pass_no)}</h2>${status(pass.status)}</div><p class="panel-note">${esc(pass.consignee_name)} · ${esc(label(pass.pass_type))} · ${date(pass.pass_date)}</p></div><div class="flex flex-wrap gap-2">${actionButtons(pass)}${button('Back to register', 'data-view="passes"', 'secondary')}</div></div><div class="document-grid">${[['Pass date', date(pass.pass_date)], ['Directorate / project', `${pass.directorate} / ${pass.project}`], ['Reference', pass.reference_no || '—'], ['Consignee', pass.consignee_name], ['Purpose', pass.purpose], ['Authority', pass.authority], ['Expected return', date(pass.expected_return_date)], ['Actual return', date(pass.actual_return_date)], ['Security control', pass.security_control_no || '—'], ['Rejection reason', pass.rejection_reason || '—']].map(([key, value]) => `<div><strong>${esc(key)}</strong><span>${esc(value)}</span></div>`).join('')}</div><section class="mt-6"><h3 class="panel-title">Material items</h3><div class="table-wrap mt-3"><table class="data-table"><thead><tr><th>Code</th><th>Material</th><th>Serial / batch</th><th>Quantity</th><th>Unit</th><th>Description</th></tr></thead><tbody>${pass.items.map((item) => `<tr><td>${esc(item.item_code || '—')}</td><td>${esc(item.item_name)}</td><td>${esc([item.serial_no, item.batch_no].filter(Boolean).join(' / ') || '—')}</td><td>${esc(item.quantity)}</td><td>${esc(item.unit_of_measure)}</td><td>${esc(item.description || '—')}</td></tr>`).join('')}</tbody></table></div></section></section>`); }

function openModal(content) { document.body.insertAdjacentHTML('beforeend', `<div class="modal-backdrop" role="dialog" aria-modal="true" aria-label="MGP action dialog"><section class="modal">${content}</section></div>`); document.querySelector('.modal-backdrop .field input, .modal-backdrop .field textarea, .modal-backdrop .field select')?.focus(); }
function closeModal() { document.querySelector('.modal-backdrop')?.remove(); }
function transitionModal(id, transition) { const labels = { reject: ['Reject gate pass', 'A written reason becomes part of the immutable workflow history.', '<label class="field">Rejection reason<textarea name="reason" required></textarea></label>'], 'pass-out': ['Pass out material', 'Record the physical gate security-control number before confirming.', '<label class="field">Security control number<input name="security_control_no" required></label>'], return: ['Mark material returned', 'Record the actual physical return date.', `<label class="field">Actual return date<input name="actual_return_date" type="date" value="${new Date().toISOString().slice(0, 10)}" required></label>`], submit: ['Submit for approval', 'Once submitted, the business fields are locked pending independent decision.', ''], approve: ['Approve gate pass', 'Approval is independently validated by the server.', ''] }; const [title, note, fields] = labels[transition]; openModal(`<form id="transitionForm" data-id="${id}" data-transition="${transition}"><div class="flex justify-between gap-4"><div><p class="page-eyebrow">CONTROLLED WORKFLOW</p><h2 class="mt-1 text-2xl font-semibold text-[#122f43]">${title}</h2><p class="mt-2 text-sm text-slate-500">${note}</p></div>${button('Close', 'type="button" data-action="close-modal"', 'ghost small')}</div><div class="mt-5">${fields}</div><div class="mt-6 flex gap-2">${button('Confirm action', 'type="submit"')}${button('Cancel', 'type="button" data-action="close-modal"', 'secondary')}</div></form>`); }
function previewPdf(pass) { const model = gatePassDocument(pass, state.profile.organization); openModal(`<div class="no-print mb-5 flex items-start justify-between gap-5"><div><p class="page-eyebrow">OFFICIAL DOCUMENT</p><h2 class="mt-1 text-2xl font-semibold text-[#122f43]">A4 gate-pass preview</h2><p class="mt-1 text-sm text-slate-500">Review the printable record, then print or download the generated PDF.</p></div><div class="flex gap-2">${button('Print', 'data-action="print-pdf"', 'ghost small')}${button('Download PDF', `data-action="download-pdf" data-id="${pass.id}"`, 'small')}${button('Close', 'data-action="close-modal"', 'secondary small')}</div></div><article class="document"><header class="document-header"><div><div class="font-mono text-xs tracking-[.16em] text-cyan-200">MATERIAL GATE PASS</div><h3 class="mt-1 text-2xl font-semibold">${esc(model.organization)}</h3><p class="mt-1 text-sm text-cyan-50">${esc(model.address)}</p></div><div class="text-right"><div class="font-mono text-xs text-cyan-200">OFFICIAL RECORD</div><div class="mt-2 font-mono text-lg font-bold">${esc(model.passNo)}</div><div class="mt-2">${status(pass.status)}</div></div></header><section class="document-grid">${model.fields.map(([key, value]) => `<div><strong>${esc(key)}</strong><span>${esc(value)}</span></div>`).join('')}</section><h4 class="mt-6 font-semibold">Material details</h4><table class="data-table mt-2 min-w-0 text-xs"><thead><tr><th>#</th><th>Code</th><th>Material</th><th>Serial</th><th>Quantity</th><th>Unit</th><th>Description</th></tr></thead><tbody>${model.items.map((item) => `<tr>${item.map((value) => `<td>${esc(value)}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="mt-16 grid grid-cols-3 gap-8 text-xs"><div class="border-t border-slate-500 pt-2 font-semibold">Prepared / Inventory</div><div class="border-t border-slate-500 pt-2 font-semibold">Approved / Issuing</div><div class="border-t border-slate-500 pt-2 font-semibold">Security / Return</div></div></article>`); }

const routes = { dashboard: dashboardView, passes: passesView, create: () => createView(), inventory: () => mastersView('inventory'), consignees: () => mastersView('consignees'), reports: reportsView, audit: auditView, users: usersView, settings: settingsView, backup: backupView, detail: () => detailView(state.selectedId) };
async function go(view, id = null) { state.view = view; if (id) state.selectedId = id; try { await routes[view](); } catch (error) { shell('Service unavailable', 'The backend could not complete this request.', `<section class="panel"><div class="notice error">${esc(error.message)}</div>${button('Return to overview', 'data-view="dashboard"')}</section>`); } }
function csv(rows) { if (!rows.length) return ''; const keys = Object.keys(rows[0]); const quote = (value) => `"${String(value ?? '').replaceAll('"', '""')}"`; return [keys, ...rows.map((row) => keys.map((key) => row[key]))].map((row) => row.map(quote).join(',')).join('\n'); }
function download(filename, contents) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([contents], { type: 'text/csv;charset=utf-8' })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }

app.addEventListener('click', async (event) => {
  const node = event.target.closest('[data-action],[data-view]'); if (!node) return;
  try {
    if (node.dataset.view) return go(node.dataset.view);
    const { action } = node.dataset;
    if (action === 'logout') { await logout(); loginView(); return; }
    if (action === 'open-pass') return go('detail', node.dataset.id);
    if (action === 'edit-pass') return createView(node.dataset.id);
    if (action === 'transition') return transitionModal(node.dataset.id, node.dataset.transition);
    if (action === 'revise-pass') { const pass = await api(`/mgp/gate-passes/${node.dataset.id}/revise`, { method: 'POST', body: JSON.stringify({}) }); setNotice(`Revision ${pass.pass_no} was created as a new draft.`); return go('detail', pass.id); }
    if (action === 'preview-pdf') return previewPdf(await api(`/mgp/gate-passes/${node.dataset.id}`));
    if (action === 'download-pdf') return downloadGatePassPdf(await api(`/mgp/gate-passes/${node.dataset.id}`), state.profile.organization);
    if (action === 'print-pdf') return window.print();
    if (action === 'close-modal') return closeModal();
    if (action === 'add-item') return document.querySelector('#items').insertAdjacentHTML('beforeend', itemRow());
    if (action === 'remove-item') return node.closest('.item-row').remove();
    if (action === 'new-master') return document.querySelector('#masterEditor').innerHTML = masterForm(node.dataset.type);
    if (action === 'edit-master') { const rows = node.dataset.type === 'inventory' ? state.inventory : state.consignees; return document.querySelector('#masterEditor').innerHTML = masterForm(node.dataset.type, rows.find((row) => row.id === node.dataset.id)); }
    if (action === 'cancel-master') return document.querySelector('#masterEditor').innerHTML = '';
    if (action === 'archive-master') { if (!window.confirm('Archive this master record? Historic gate passes will retain their snapshot.')) return; await api(`/mgp/${node.dataset.type}/${node.dataset.id}/archive`, { method: 'POST', body: JSON.stringify({}) }); setNotice('Master record archived.'); return mastersView(node.dataset.type); }
    if (action === 'export-master') { const rows = await api(`/mgp/${node.dataset.type}/export`); download(`${node.dataset.type}.csv`, csv(rows)); setNotice('CSV export downloaded.'); return mastersView(node.dataset.type); }
    if (action === 'new-user') return document.querySelector('#userEditor').innerHTML = userForm();
    if (action === 'edit-user') return document.querySelector('#userEditor').innerHTML = userForm(JSON.parse(decodeURIComponent(node.dataset.user)));
    if (action === 'cancel-user') return document.querySelector('#userEditor').innerHTML = '';
  } catch (error) { setNotice(error.message, 'error'); await go(state.view); }
});

app.addEventListener('submit', async (event) => {
  event.preventDefault(); const form = event.target;
  try {
    if (form.id === 'loginForm') { const values = new FormData(form); await login(values.get('email'), values.get('password')); state.profile = await api('/mgp/me'); return go('dashboard'); }
    if (form.id === 'filterForm') { const values = Object.fromEntries(new FormData(form).entries()); await fetchPasses(values); setNotice(`${state.passes.length} matching records.`, 'info'); return passesView(); }
    if (form.id === 'passForm') { const data = Object.fromEntries(new FormData(form).entries()); data.items = [...form.querySelectorAll('.item-row')].map((row) => Object.fromEntries([...row.querySelectorAll('input')].map((input) => [input.name, input.value]))); const id = form.dataset.id; await api(id ? `/mgp/gate-passes/${id}` : '/mgp/gate-passes', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(data) }); setNotice(id ? 'Draft updated.' : 'Draft created with an atomic official pass number.'); return go('passes'); }
    if (form.id === 'masterForm') { const data = Object.fromEntries(new FormData(form).entries()); const id = form.dataset.id; await api(id ? `/mgp/${form.dataset.type}/${id}` : `/mgp/${form.dataset.type}`, { method: id ? 'PATCH' : 'POST', body: JSON.stringify(data) }); setNotice('Master record saved.'); return mastersView(form.dataset.type); }
    if (form.id === 'transitionForm') { const data = Object.fromEntries(new FormData(form).entries()); await api(`/mgp/gate-passes/${form.dataset.id}/${form.dataset.transition}`, { method: 'POST', body: JSON.stringify(data) }); closeModal(); setNotice('Workflow transition completed.'); return go('detail', form.dataset.id); }
    if (form.id === 'settingsForm') { const data = Object.fromEntries(new FormData(form).entries()); state.profile.organization = await api('/mgp/settings/organization', { method: 'PATCH', body: JSON.stringify(data) }); setNotice('Organization settings saved.'); return go('settings'); }
    if (form.id === 'userForm') { const data = Object.fromEntries(new FormData(form).entries()); const id = form.dataset.id; await api(id ? `/mgp/users/${id}` : '/mgp/users', { method: id ? 'PATCH' : 'POST', body: JSON.stringify(data) }); setNotice(id ? 'MGP user updated.' : 'MGP user provisioned.'); return go('users'); }
  } catch (error) { const target = form.id === 'loginForm' ? document.querySelector('#loginNotice') : null; if (target) target.innerHTML = `<div class="notice error">${esc(error.message)}</div>`; else { setNotice(error.message, 'error'); await go(state.view); } }
});

(async () => { if (await restoreSession()) { try { state.profile = await api('/mgp/me'); await go('dashboard'); return; } catch { await logout(); } } loginView(); })();
